<html lang="0">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1" name="danxy"/>
  <title>
   Dhocemarket.com
  </title>
  <script src="https://cdn.tailwindcss.com">
  </script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&amp;display=swap" rel="stylesheet"/>
  <style>
   body {
      font-family: 'Inter', sans-serif;
    }
  </style>
 </head>
 <body class="relative min-h-screen bg-gray-900 text-white">
  <img alt="A warm, professional personal photo of a smiling person in a modern office environment with natural light and plants" class="fixed inset-0 w-full h-full object-cover object-center opacity-30 -z-10" height="1080" src="https://files.catbox.moe/adp0nn.jpg" width="1080"/>
  <header class="bg-black bg-opacity-60 backdrop-blur-sm sticky top-0 z-20">
   <nav class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
     <a class="text-2xl font-semibold text-blue-400" href="#">
      DHOCE MARKET
     </a>
     <ul class="hidden md:flex space-x-8 text-white font-medium">
      <li>
        <p><article class="block px-2 hover:text-blue-400 transition" href="#contact"></p>
  </header>
    <article class="bg-black bg-opacity-60 backdrop-blur-sm rounded-lg p-6">
     <img 
  alt="Dhocemarket..." 
  class="rounded-md mb-4 object-cover w-[1280px] h-[1280px] mx-auto" 
  src="https://files.catbox.moe/aq7vgp.jpg" 
  width="10" 
  height="10"
/>
     <h2 class="text-2xl font-semibold text-blue-400 mb-2">
      PP ASLI DHOCE
</a>
      </li>
     </ul>
    </div>
   </nav>
  </header>
     </h2>
     <p class="text-gray-300 flex-grow">
      MAU BUY LOGO ATAU BELI FOLLOWERS IG/TT BISA ORDER DI BAWAH
     </p>
     <p class="mt-4 font-bold text-lg text-blue-300">
      LIST BY DHOCE
     </p>
    </h2>
    <ol class="list-decimal list-inside space-y-4 text-gray-300 text-lg">
       <p>🧩 Jual Logo Unik & Profesional – Cerminkan Identitas Brand Anda!<p>
         
       <p>Ingin bisnis Anda terlihat lebih profesional, mudah diingat, dan terpercaya? Kami menyediakan jasa pembuatan logo berkualitas tinggi dengan desain eksklusif yang sesuai dengan karakter brand Anda!</p>
     
      <p>🔹 Apa yang Anda Dapatkan?

Desain logo unik (bukan template)

File siap cetak (PNG, JPG, PDF, dan AI/PSD jika diperlukan)

Revisi desain (sesuai paket)

Desain bisa digunakan untuk sosial media, produk, banner, dll
</p>
     
     <p>🔹 Cocok untuk:

UMKM, toko online, brand fashion, food & beverage, jasa, personal branding, dan lainnya!</p>

<p>🔹 Kenapa pilih kami?

Desainer berpengalaman

Proses cepat dan komunikatif

Hasil memuaskan, bisa langsung digunakan</p>

<p>💬 “Logo bukan sekadar gambar, tapi wajah dari brand Anda!”<p>
  
  </p>📩 Hubungi sekarang untuk konsultasi gratis atau lihat portofolio kami!</p>
     </li>
     <p class="mt-4 font-bold text-lg text-blue-300">
     </li>
     *!JIKA DI WHATSAPP TIDAK DI RESPON KE INSTAGRAM!*
     </p>
     <h2>
      <p>HATI HATI TERHADAP CLONE INGAT WA DAN IG REAL HANYA DI WEBSITE INI YANG LAIN CLONE</p>
      <p>     </article>
    <article class="bg-black bg-opacity-0 backdrop-blur-sm rounded-lg p-6 flex flex-col shadow-lg hover:shadow-blue-400 transition-shadow"></p>
  </h2>
<section class="overflow-x-auto scroll-smooth snap-x snap-mandatory px-4 mb-20" id="products">
  <div class="flex space-x-6 w-max">

        <!-- Product 1-->
    <article class="snap-start bg-black bg-opacity-60 backdrop-blur-sm rounded-lg p-6 flex-shrink-0 w-[400px] shadow-lg hover:shadow-green-400 transition-shadow duration-300 delay-[100000000s]">
      <img src="https://files.catbox.moe/8ze28b.png" alt="Product 4" class="rounded-md mb-4 object-cover w-full h-48" />
      <h2 class="text-2xl font-semibold text-green-400 mb-2">VPS EU PERFORMANCE</h2>
      <p class="text-gray-300">GARANSI 7 DAY, PERFORMA TINGGI, FREE SETUP</p>
      <p class="mt-4 font-bold text-lg text-green-300">Rp 50.000</p>
      <a class="mt-6 inline-flex items-center justify-center bg-green-500 hover:bg-green-600 text-white font-semibold py-3 rounded-md transition w-full" href="https://wa.me/6285894100506"_blank" rel="noopener noreferrer">
        <i class="fab fa-whatsapp mr-2 text-xl"></i> Order via WhatsApp
      </a>
    </article>

    <!-- Product 2 -->
    <article class="snap-start bg-black bg-opacity-60 backdrop-blur-sm rounded-lg p-6 flex-shrink-0 w-[400px] shadow-lg hover:shadow-green-400 transition-shadow duration-300 delay-[100000000s]">
      <img src="https://files.catbox.moe/8ze28b.png" alt="Product 4" class="rounded-md mb-4 object-cover w-full h-48" />
      <h2 class="text-2xl font-semibold text-green-400 mb-2">VPS EU PERFORMANCE</h2>
      <p class="text-gray-300">GARANSI 7 DAY, PERFORMA TINGGI, FREE SETUP</p>
      <p class="mt-4 font-bold text-lg text-green-300">Rp 50.000</p>
      <a class="mt-6 inline-flex items-center justify-center bg-green-500 hover:bg-green-600 text-white font-semibold py-3 rounded-md transition w-full" href="https://wa.me/6285894100506targettarget="_blank" rel="noopener noreferrer">
        <i class="fab fa-whatsapp mr-2 text-xl"></i> Order via WhatsApp
      </a>
    </article>

    <!-- Product 3 -->
    <article class="snap-start bg-black bg-opacity-60 backdrop-blur-sm rounded-lg p-6 flex-shrink-0 w-[400px] shadow-lg hover:shadow-green-400 transition-shadow duration-300 delay-[100000000s]">
      <img src="https://files.catbox.moe/8ze28b.png" alt="Product 3" class="rounded-md mb-4 object-cover w-full h-48" />
      <h2 class="text-2xl font-semibold text-green-400 mb-2">VPS SG FAST</h2>
      <p class="text-gray-300">GARANSI 3 DAY, PING RENDAH, FREE BACKUP</p>
      <p class="mt-4 font-bold text-lg text-green-300">Rp 45.000</p>
      <a class="mt-6 inline-flex items-center justify-center bg-green-500 hover:bg-green-600 text-white font-semibold py-3 rounded-md transition w-full" href="https://wa.me/6285894100506"_blank" rel="noopener noreferrer">
        <i class="fab fa-whatsapp mr-2 text-xl"></i> Order via WhatsApp
      </a>
    </article>

    <!-- Product 5 -->
    <article class="snap-start bg-black bg-opacity-60 backdrop-blur-sm rounded-lg p-6 flex-shrink-0 w-[400px] shadow-lg hover:shadow-green-400 transition-shadow duration-300 delay-[100000000s]">
      <img src="https://files.catbox.moe/8ze28b.png" alt="Product 4" class="rounded-md mb-4 object-cover w-full h-48" />
      <h2 class="text-2xl font-semibold text-green-400 mb-2">VPS EU PERFORMANCE</h2>
      <p class="text-gray-300">GARANSI 7 DAY, PERFORMA TINGGI, FREE SETUP</p>
      <p class="mt-4 font-bold text-lg text-green-300">Rp 50.000</p>
      <a class="mt-6 inline-flex items-center justify-center bg-green-500 hover:bg-green-600 text-white font-semibold py-3 rounded-md transition w-full" href="https://wa.me/6285894100506target="_blank" rel="noopener noreferrer">
        <i class="fab fa-whatsapp mr-2 text-xl"></i> Order via WhatsApp
      </a>
    </article>
</section> 
     </h2>
<!-- Kontak Kami di Bawah Tengah -->
<section id="contact" class="mt-24 mb-12 text-center px-4">
  <h2 class="text-3xl font-bold text-blue-400 mb-4">Kontak Kami</h2>
  <p class="text-gray-300 mb-6">
    Jika Anda memiliki pertanyaan atau ingin melakukan pemesanan, hubungi kami melalui:
  </p>

  <div class="flex justify-center flex-wrap gap-4 mb-4">
    <!-- Tombol WhatsApp -->
    <a href="https://wa.me/6285894100506
       target="_blank" rel="noopener noreferrer"
       class="flex items-center gap-2 bg-green-500 hover:bg-green-600 text-white font-semibold px-6 py-3 rounded-md transition">
      <i class="fab fa-whatsapp text-xl"></i> WhatsApp
    </a>

    <!-- Tombol Instagram -->
    <a href="https://instagram.com/fiky4you_"
       target="_blank" rel="noopener noreferrer"
       class="flex items-center gap-2 bg-pink-500 hover:bg-pink-600 text-white font-semibold px-6 py-3 rounded-md transition">
      <i class="fab fa-instagram text-xl"></i> Instagram
    </a>
  </div>

  <p class="text-sm text-gray-400">
    *Pastikan hanya menghubungi kontak resmi kami untuk keamanan transaksi Anda.
  </p>
</section>
  </p>
</section>
    </p>
  <div>
</section>
</a>
  </script>
 </body>
</html>
